[package]
name = "openconnect"
version.workspace = true
edition.workspace = true
license.workspace = true
links = "openconnect"

[dependencies]
log.workspace = true
is_executable.workspace = true

[build-dependencies]
cc = "1"
autotools = "0.2"
pkg-config = "0.3"
fs_extra = "1"
