name: Pre Release

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types: [completed]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DEBFULLNAME: "Kevin Yue"
      DEBEMAIL: "yuezk001@gmail.com"

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initial variables
        id: vars
        run: |
          TAG=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1 | cut -c 2-)
          echo ::set-output name=VERSION::"${TAG}+SNAPSHOT$(date -u +"%Y%m%d%H%M%S")"
          echo ::set-output name=TAG::${TAG}   

      - name: Update debian/changelog
        run: |
          sudo apt install devscripts
          git log --format="%s" v${{ steps.vars.outputs.TAG }}.. | xargs -L1 dch -v ${{ steps.vars.outputs.VERSION }}-1ppa1

      - name: "Archive all"
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all
          git-archive-all \
            --force-submodules \
            --prefix=globalprotect-openconnect-${{ steps.vars.outputs.VERSION }}/ \
            ./globalprotect-openconnect_${{ steps.vars.outputs.VERSION }}.orig.tar.gz

      - name: "Packaging"
        run: |
          sudo apt update
          sudo apt install qtbase5-dev libqt5websockets5-dev qtwebengine5-dev qttools5-dev debhelper
          mkdir build-debian && cd build-debian
          cp ../*.tar.gz .
          tar xf *.tar.gz
          cd globalprotect-openconnect-${{ steps.vars.outputs.VERSION }}
          fakeroot dpkg-buildpackage -uc -us -sa

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: "latest"
          prerelease: true
          title: "globalprotect-openconnect_${{ steps.vars.outputs.VERSION }}"
          files: |
            *.tar.gz
            build-debian/*.deb